apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PVC_SIZE
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    required: true
    value: 256Mi
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  ### Backup-Container starts here ###
  - name: "DATABASE_DEFAULT_PORT"
    description: "The configured port for the database service"
    value: "5432"
  - name: "BACKUP_STRATEGY"
    description: "The strategy to use for backups; for example daily, or rolling."
    required: true
    value: "rolling"
  - name: "NUM_BACKUPS"
    description: "The number of backup files to be retained.  Used for the `daily` backup strategy.  Ignored when using the `rolling` backup strategy."
    required: false
    value: "5"
  - name: "DAILY_BACKUPS"
    description: "The number of daily backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "7"
  - name: "WEEKLY_BACKUPS"
    description: "The number of weekly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "4"
  - name: "MONTHLY_BACKUPS"
    displayName: "Number of Monthly Backups to Retain"
    description: "The number of monthly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "1"
  - name: "JOB_SERVICE_ACCOUNT"
    description: "Name of the Service Account To Exeucte the Job As."
    value: "default"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    description: "The number of failed jobs that will be retained"
    value: "2"
    required: true
  - name: "JOB_BACKOFF_LIMIT"
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    name: PVC_SIZE
    value: 256Mi
  - name: CRON_MINUTES
    description: Random number, 0-60, for scheduling cronjobs
    from: "[0-5]{1}[0-9]{1}"
    generate: expression
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    required: true
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: gba-${ZONE}-database
      labels:
        app: gba-${ZONE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${DB_PVC_SIZE}
      storageClassName: netapp-file-standard
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: gba-${ZONE}-database
      labels:
        app: gba-${ZONE}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: gba-${ZONE}-database
      labels:
        app: gba-${ZONE}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - gba
            from:
              kind: ImageStreamTag
              name: gba-${ZONE}-database:${IMAGE_TAG}
      selector:
        deploymentconfig: gba-${ZONE}-database
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        activeDeadlineSeconds: 21600
      template:
        metadata:
          name: gba-${ZONE}-database
          labels:
            app: gba-${ZONE}
            deploymentconfig: gba-${ZONE}-database
        spec:
          volumes:
            - name: gba-${ZONE}-database
              persistentVolumeClaim:
                claimName: gba-${ZONE}-database
          containers:
            - name: gba
              image: gba-${ZONE}-database:${IMAGE_TAG}
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                failureThreshold: 5
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 1
              livenessProbe:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
                failureThreshold: 5
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 1
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: gba-${ZONE}-database
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gba-${ZONE}-database
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: gba-${ZONE}-database
                      key: database-user
              volumeMounts:
                - name: gba-${ZONE}-database
                  mountPath: /var/lib/postgresql
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: gba-${ZONE}
      name: gba-${ZONE}-database
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        deploymentconfig: gba-${ZONE}-database
      sessionAffinity: None
      type: ClusterIP
  ### Backup-Container starts here ###
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: gba-${ZONE}-database-backup
      labels:
        app: gba-${ZONE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${PVC_SIZE}"
      storageClassName: netapp-file-standard
  - kind: CronJob
    apiVersion: "batch/v1"
    metadata:
      name: gba-${ZONE}-database-backup
      labels:
        app: gba-${ZONE}
        cronjob: gba-${ZONE}
    spec:
      schedule: "${CRON_MINUTES} 8 * * *" # Run daily at 8:xx AM UTC
      concurrencyPolicy: "Replace"
      successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
      failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
      jobTemplate:
        metadata:
          labels:
            app: gba-${ZONE}
            cronjob: gba-${ZONE}
        spec:
          backoffLimit: ${{JOB_BACKOFF_LIMIT}}
          template:
            metadata:
              labels:
                app: gba-${ZONE}
                cronjob: gba-${ZONE}
            spec:
              containers:
                - name: gba-${ZONE}
                  image: "bcgovimages/backup-container:latest"
                  command:
                    - "/bin/bash"
                    - "-c"
                    - "/backup.sh -1"
                  volumeMounts:
                    - mountPath: "/backups/"
                      name: "backup"
                  env:
                    - name: BACKUP_DIR
                      value: "/backups/"
                    - name: BACKUP_STRATEGY
                      value: "${BACKUP_STRATEGY}"
                      optional: true
                    - name: NUM_BACKUPS
                      value: "${NUM_BACKUPS}"
                      optional: true
                    - name: DAILY_BACKUPS
                      value: "${DAILY_BACKUPS}"
                      optional: true
                    - name: WEEKLY_BACKUPS
                      value: "${WEEKLY_BACKUPS}"
                      optional: true
                    - name: MONTHLY_BACKUPS
                      value: "${MONTHLY_BACKUPS}"
                      optional: true
                    - name: DATABASE_SERVICE_NAME
                      value: "gba-${ZONE}-database"
                    - name: DEFAULT_PORT
                      value: ${DATABASE_DEFAULT_PORT}
                    - name: POSTGRESQL_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: "gba-${ZONE}-database"
                          key: "database-name"
                    - name: DATABASE_USER
                      valueFrom:
                        secretKeyRef:
                          name: gba-${ZONE}-database
                          key: "database-user"
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: gba-${ZONE}-database
                          key: "database-password"
              volumes:
                - name: backup
                  persistentVolumeClaim:
                    claimName: gba-${ZONE}-database-backup
              restartPolicy: "Never"
              terminationGracePeriodSeconds: 30
              activeDeadlineSeconds: 1600
              dnsPolicy: "ClusterFirst"
              serviceAccountName: "${JOB_SERVICE_ACCOUNT}"
              serviceAccount: "${JOB_SERVICE_ACCOUNT}"
